swagger: "2.0"
info:
    description: This is the swagger OpenAPI file that goes with our sever code
    version: "1.0.0"
    title: Kartavyas Mail Handler
consumes:
    - application/json
produces:
    - application/json

basePath: /mail

paths:
    /handler:
        post:
            operationId: web.controllers.mail_controller.send_mail
            tags:
                - Response
            summary: Add to sender identity and send mail
            description: Recieves form body response and sends mail
            consumes:
                - multipart/form-data
            parameters:
                - in: "body"
                  name: message
                  description: Sender details and message
                  schema:
                      type: object
                      properties:
                          firstName:
                              type: string
                              description: First name of sender
                          lastName:
                              type: string
                              description: Last name of sender
                          email:
                              type: string
                              description: Email address of sender
                          message:
                              type: string
                              description: Message from sender
            responses:
                200:
                    description: Successfully sent mail
